- mkdocs.yml
> mkdocs.yml: add google analytics

- docs/osf-trolling-list/build_process.md
> docs/osf-trolling-list/build_process.md: add wget/dpkg and VM apprach

- docs/CNAME
> docs/CNAME: fix problem with gh-pages custom domain

- docs/quality-principles/introduction.md
- mkdocs.yml
> docs/quality-principles: add introduction

- docs/variants/firewall.md
> docs/variants/firewall.md: add marketing description

- docs/value-prop/certification-program/overview.md
- mkdocs.yml
> value-prop/certification-program: initial versions with overview

- docs/variants/asus_kgpe_d16/setup.md
> docs/variants/asus_kgpe_d16/setup.md: update RteCtrl

- docs/variants/asus_kgpe_d16/setup.md
docs/variants/asus_kgpe_d16/setup.md: change IP address for one of RTE connected with Asus KGPE-D16
> Change IP address for one of RTE connected with Asus KGPE-D16

- docs/variants/asus_kgpe_d16/releases.md
- mkdocs.yml
> docs/variants/asus_kgpe_d16/releases.md: add first release

- docs/osf-trolling-list/trusted_computing.md
- mkdocs.yml
> docs/osf-trolling-list: initial trusted computing questions

- docs/osf-trolling-list/osf_issues_taxonomy.md
> WIP: OSFTTL: add candidates for questions

- docs/variants/asus_kgpe_d16/dasharo-compatibility/generic-test-setup.md
- docs/variants/asus_kgpe_d16/dasharo-compatibility/index.md
- docs/variants/asus_kgpe_d16/dasharo/100-coreboot-base-port.md
KGPE-D16:
1. Add coreboot base port test cases description.
2. Add generic test setup file.
3. Add index file.
> KGPE-D16 test cases description 

- docs/variants/asus_kgpe_d16/fan-control.md
- mkdocs.yml
> docs/variants/asus_kgpe_d16/fan-control.md: add doc about fan control

- docs/dev-proc/source-code-structure.md
> docs/dev-proc/source-code-structure.md: Fix rendering

- docs/variants/asus_kgpe_d16/spi-wp.md
- mkdocs.yml
> docs/variants/asus_kgpe_d16/spi-wp.md: add manual for SPI WP

- docs/dev-proc/source-code-structure.md
Signed-off-by: Krystian Hebel <krystian.hebel@3mdeb.com>
> docs/dev-proc/source-code-structure.md: describe git remotes

- docs/ecosystem/testing-infrastructure/dasharo-compatibility-specification/dmidecode.md
- docs/variants/asus_kgpe_d16/dasharo-compatibility/dmidecode.md
- docs/variants/asus_kgpe_d16/dasharo-compatibility/index.md
Dmidecode test procedures for ASUS KGPE-D16
> Dmidecode kgpe

- docs/variants/asus_kgpe_d16/releases.md
> docs/variants/asus_kgpe_d16/releases.md: add v0.2.0 release

- docs/ecosystem/roadmap.md
- docs/osf-trivia-list/deployment.md
- docs/variants/dell_optiplex/building-manual.md
- docs/variants/dell_optiplex/installation-manual.md
- docs/variants/dell_optiplex/overview.md
- docs/variants/hardware-compatibility-list.md
- mkdocs.yml
Troubleshooting section for Dell OptiPlex was split to make further
references to flashrom issues easier. TBD sentence was moved to
Ecosystem Roadmap to create better place for future project ideas.
> docs/variants/dell_optiplex: split troubleshooting

- docs/variants/asus_kgpe_d16/releases.md
> docs/variants/asus_kgpe_d16/releases.md: add v0.3.0 release notes

- docs/variants/asus_kgpe_d16/dasharo-security/verified-boot.md
Signed-off-by: Przemyslaw Sulewski przemyslaw.sulewski@3mdeb.com
> kgpe-d16: add verified boot test suite description

- docs/variants/clevo_nv41/openness_analysis.md
- mkdocs.yml
> clevo_nv41/openness_analysis.md: Add openness percentage analysis

- docs/variants/clevo_nv41/post_install.md
- mkdocs.yml
> clevo_nv41: add post-installation steps doc

- docs/variants/clevo_nv41/releases.md
> clevo_nv41/releases.md: Fix newsletter subscription link

- docs/variants/clevo_nv41/fwupd_usage.md
- docs/variants/clevo_nv41/lvfs_report.md
- mkdocs.yml
> Add nv4x fwupd verification documentation

- docs/variants/clevo_nv41/fwupd_usage.md
> docs/variants/clevo_nv41/fwupd_usage.md: fix typo

- docs/variants/clevo_nv41/releases.md
> variants/clevo_nv41/releases.md v1.0.0

- docs/variants/clevo_nv41/flashing_external.md
> nv41/flashing_external.md: Update external flashing documentation 

- docs/dev-proc/smbios-rules.md
- mkdocs.yml
> docs/dev-proc/smbios-rules.md: add SMBIOS conventions doc

- docs/variants/talos_2/conferences.md
- mkdocs.yml
> talos_2/conferences: Add conferences

- docs/variants/asus_kgpe_d16/setup.md
> docs/variants/asus_kgpe_d16/setup.md: fix bullet point formatting

- docs/ecosystem/overview.md
- docs/index.md
- docs/osf-trivia-list/deployment.md
- docs/transparent-validation/rte/v1.1.0/reference-os.md
- docs/value-prop/overview.md
- docs/variants/asus_kgpe_d16/dasharo-security/tpm-support.md
- docs/variants/asus_kgpe_d16/dasharo-security/verified-boot.md
- docs/variants/asus_kgpe_d16/tpm-mboot.md
- docs/variants/clevo_nv41/openness_analysis.md
- docs/variants/dell_optiplex/firmware-update.md
- docs/variants/dell_optiplex/initial-deployment.md
- docs/variants/dell_optiplex/overview.md
- mkdocs.yml
> Improve navigation across all documentation

- docs/transparent-validation/sd-wire/usage-validation.md
Performed changes:
* Remove white spaces
* Change command which is showing switching SDWire to the DUT
> Fix documentation of SDWire

- docs/variants/clevo_nv41/releases.md
> docs/variants/clevo_nv41/releases.md: add v1.0.1 release info

- docs/unified-test-documentation/dasharo-compatibility/31E-display-ports-and-lcd.md
- docs/unified-test-documentation/dasharo-compatibility/31F-audio-subsystem.md
- docs/unified-test-documentation/dasharo-compatibility/31H-usb-type-c.md
- mkdocs.yml
> Unified test documentation: display ports, audio and USB C test suites

- docs/unified-test-documentation/dasharo-compatibility/312-nvme-support.md
- docs/unified-test-documentation/dasharo-compatibility/315-network-boot.md
- docs/unified-test-documentation/dasharo-compatibility/316-sdcard-reader.md
- docs/unified-test-documentation/dasharo-compatibility/317-usb-camera.md
- docs/unified-test-documentation/dasharo-compatibility/318-m2-wifi-bluetooth.md
- mkdocs.yml
> Unified test documentation: test suites dedicated for laptops

- docs/unified-test-documentation/dasharo-compatibility/30L-memtest-payload-support.md
- mkdocs.yml
> Unified test documentation: memtest

- docs/unified-test-documentation/dasharo-compatibility/31A-windows-booting.md
- docs/unified-test-documentation/dasharo-compatibility/31J-sleep-mode.md
- mkdocs.yml
> Unified test documentation: Windows booting and sleep mode

- docs/unified-test-documentation/dasharo-compatibility/30P-uefi-shell.md
- docs/unified-test-documentation/dasharo-compatibility/S30-fan-control.md
- docs/unified-test-documentation/dasharo-compatibility/S31-coreboot-fan-control.md
- mkdocs.yml
> Unified test documentation: fan control

- docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
- mkdocs.yml
> Unified test documentation: embedded controller test suite

- docs/unified-test-documentation/overview.md
- mkdocs.yml
> docs/unified-test-documentation/overview.md: add documentation overview

- docs/variants/tuxedo_ibs15/testing-configuration.md
- mkdocs.yml
> docs/variants/tuxedo_ibs15/: add platform hardware matrix

- docs/variants/tuxedo_ibs15/installation.md
- docs/variants/tuxedo_ibs15/releases.md
FIXME: Add an actual e-mail address for contact for the ME update
> docs/variants/tuxedo_ibs15: add supported IME version

- docs/unified-test-documentation/dasharo-compatibility/100-coreboot-base-port.md
- docs/unified-test-documentation/overview.md
- docs/unified-test-documentation/test-matrix.md
> KGPE D16 test matrix

- docs/variants/novacustom_ns5x/building.md
- docs/variants/novacustom_ns5x/installation.md
- docs/variants/novacustom_ns5x/post_install.md
- docs/variants/novacustom_ns5x/releases.md
- docs/variants/tuxedo_ibs15/testing-configuration.md
- mkdocs.yml
Based on the Tuxedo IBS15 docs.
> Add NovaCustom NS5X documentation

- docs/variants/clevo_nv41/fwupd_usage.md
> clevo_nv41/fwupd_usage: Disable secure boot for fwupd

- docs/common-coreboot-docs/dasharo_tools_suite.md
- docs/variants/clevo_nv41/flashing_internal.md
- docs/variants/clevo_nv41/releases.md
- mkdocs.yml
> docs/variants/clevo_nv41/releases.md: add v1.1.0 changelog

- docs/projects/trenchboot-aem.md
- mkdocs.yml
- overrides/giscus.html
> projects/trenchboot-aem.md: add application with giscus system

- docs/projects/trenchboot-aem.md
> docs/projects/trenchboot-aem.md: fix experience years

- docs/projects/trenchboot-aem.md
> docs/projects/trenchboot-aem.md: apply grammar fixes

- docs/projects/trenchboot-aem.md
> docs/projects/trenchboot-aem.md: fix broken links

- docs/variants/clevo_nv41/fwupd_usage.md
> docs/variants/clevo_nv41/fwupd_usage.md: update fwupd version

- mkdocs.yml
> mkdocs.yml: fix DTS URL

- docs/common-coreboot-docs/dasharo_tools_suite.md
- docs/variants/clevo_nv41/fwupd_usage.md
> docs/variants/clevo_nv41/fwupd_usage.md: refresh before update

- docs/variants/msi_z690/test-matrix.md
> docs/variants/msi_z690/test-matrix.md: test-matrix for RC2 release

- docs/unified-test-documentation/dasharo-compatibility/306-usb-hid-and-msc-support.md
- docs/unified-test-documentation/dasharo-compatibility/312-nvme-support.md
- docs/unified-test-documentation/dasharo-compatibility/316-sdcard-reader.md
- docs/unified-test-documentation/dasharo-compatibility/317-usb-camera.md
- docs/unified-test-documentation/dasharo-compatibility/318-m2-wifi-bluetooth.md
- docs/unified-test-documentation/dasharo-compatibility/31E-display-ports-and-lcd.md
- docs/unified-test-documentation/dasharo-compatibility/31F-audio-subsystem.md
- docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
- docs/unified-test-documentation/dasharo-compatibility/31H-usb-type-c.md
- docs/unified-test-documentation/dasharo-compatibility/31I-nvme-switching.md
- docs/unified-test-documentation/dasharo-compatibility/31J-sleep-mode.md
- docs/unified-test-documentation/dasharo-compatibility/31K-minipcie-verification.md
- docs/unified-test-documentation/dasharo-compatibility/31M-emmc-support.md
- docs/unified-test-documentation/dasharo-compatibility/31M-platform-suspend-and-resume.md
- docs/unified-test-documentation/dasharo-compatibility/31W-device-tree.md
- docs/unified-test-documentation/dasharo-compatibility/323-device-tree.md
- docs/unified-test-documentation/dasharo-compatibility/S30-fan-control.md
- docs/unified-test-documentation/dasharo-security/200-tpm-support.md
- docs/unified-test-documentation/dasharo-security/201-verified-boot.md
- docs/unified-test-documentation/dasharo-security/203-measured-boot.md
- docs/variants/talos_2/test-matrix.md
- mkdocs.yml
> unified-test-documentation/dasharo-compatibility/323-device-tree.md: add file

- docs/variants/msi_z690/installation-manual.md
>  docs/variants/msi_z690/installation-manual.md: add backup drive note

- docs/variants/talos_2/installation-manual.md
- docs/variants/talos_2/releases.md
Signed-off-by: Krystian Hebel <krystian.hebel@3mdeb.com>
> docs/variants/talos_2/releases.md: add 0.5.0 release

- docs/variants/novacustom_ns5x/building.md
> novacustom_ns5x/building.md: clone upstream as origin

- docs/variants/novacustom_ns5x/building.md
> novacustom_ns5x/building.md: fix release tag format

- docs/variants/msi_z690/test-matrix.md
msi_z690/test-matrix.md: expand test matrix for phase 2 and 3
> MSI Z690 PRO: expand test matrix for phases 2nd and 3rd

- docs/common-coreboot-docs/fwupd_usage.md
- mkdocs.yml
Also update fwupd version and add link to doc in NS5x section.
FIXME: Fix links to updated checksum and signature.
> Move fwupd documentation to common docs

- docs/common-coreboot-docs/custom_logo.md
> docs/coreboot-common-docs: add persistent bootlogo instructions

- docs/variants/novacustom_ns5x/releases.md
> docs/variants/novacustom_ns5x/releases.md: add v1.1.0 release info

- docs/unified-test-documentation/dasharo-compatibility/31U-heads-bootloader-support.md
- docs/variants/novacustom_ns5x/hardware-matrix.md
- docs/variants/talos_2/releases.md
- mkdocs.yml
> docs/variants/novacustom_ns5x/hardware-matrix.md: add file

- docs/variants/msi_z690/faq.md
- docs/variants/msi_z690/overview.md
- docs/variants/msi_z690/recovery.md
- mkdocs.yml
> variants/msi_z690/recovery.md: improvements

- docs/unified-test-documentation/dasharo-compatibility/318-m2-wifi-bluetooth.md
- docs/unified-test-documentation/dasharo-compatibility/31K-minipcie-verification.md
- docs/variants/msi_z690/hardware-matrix.md
> unified-test-documentation/dasharo-compatibility: remove MAC addresses

- docs/variants/msi_z690/test-matrix.md
> Test cases for phases 4/5

- docs/unified-test-documentation/dasharo-compatibility/31A-windows-booting.md
- docs/unified-test-documentation/test-matrix.md
- docs/variants/msi_z690/test-matrix.md
- docs/variants/novacustom_ns5x/test-matrix.md
- mkdocs.yml
> Windows 10 booting test case

- docs/variants/msi_z690/memory-hcl.md
- mkdocs.yml
> docs/variants/msi_z690/memory-hcl.md: add initial page

- docs/unified-test-documentation/dasharo-compatibility/306-usb-hid-and-msc-support.md
> dasharo-compatibility/306-usb-hid-and-msc-support.md: update description tests USB001.003 and USB002.003

- docs/unified-test-documentation/dasharo-compatibility/318-m2-wifi-bluetooth.md
> dasharo-compatibility/318-m2-wifi-bluetooth.md: update test cases on Windows

- docs/unified-test-documentation/dasharo-compatibility/312-nvme-support.md
- docs/unified-test-documentation/dasharo-compatibility/316-sdcard-reader.md
Signed off by Przemysław Banasiak [przemyslaw.banasiak@3mdeb.com]
> Sd powershell docs

- docs/variants/msi_z690/releases.md
> docs/variants/msi_z690/releases.md: add v0.3.0 release info

- .markdownlint.yaml
- docs/common-coreboot-docs/custom_logo.md
- docs/ecosystem/roadmap.md
- docs/inquiries/sponsorware.md
- docs/value-prop/marketing.md
- docs/variants/asus_kgpe_d16/setup.md
- docs/variants/asus_kgpe_d16/spi-wp.md
- docs/variants/clevo_nv41/building.md
- docs/variants/clevo_nv41/lvfs_report.md
- docs/variants/dell_optiplex/releases.md
- docs/variants/msi_z690/building-manual.md
- docs/variants/msi_z690/development.md
- docs/variants/msi_z690/faq.md
- docs/variants/msi_z690/memory-hcl.md
- docs/variants/msi_z690/releases.md
- docs/variants/novacustom_ns5x/building.md
- docs/variants/novacustom_ns5x/releases.md
- docs/variants/talos_2/releases.md
- docs/variants/tuxedo_ibs15/building.md
> mass pre-commit fixes

- docs/variants/talos_2/installation-manual.md
Addresses https://github.com/Dasharo/dasharo-issues/issues/79.
> Fix Talos II installation instructions

- docs/transparent-validation/muxpi/basic-validation.md
Signed off by Przemysław Banasiak [przemyslaw.banasiak@3mdeb.com]
> add connection method img

- docs/osf-trivia-list/me.md
- docs/unified-test-documentation/dasharo-performance/401-cpu-temperature.md
> dasharo-performance/401-cpu-temperature.md: add file

- docs/variants/protectli_fw6/building-manual.md
- docs/variants/protectli_fw6/installation-manual.md
- docs/variants/protectli_fw6/overview.md
- docs/variants/protectli_fw6/releases.md
- mkdocs.yml
> Add Protectli FW6 documentation

- docs/unified-test-documentation/dasharo-compatibility/320-fwupd-firmware-update.md
- docs/unified-test-documentation/dasharo-performance/401-cpu-temperature.md
- docs/variants/msi_z690/overview.md
- docs/variants/protectli_fw6/hardware-matrix.md
- docs/variants/protectli_fw6/installation-manual.md
- docs/variants/protectli_fw6/releases.md
- docs/variants/protectli_fw6/test-matrix.md
- docs/variants/protectli_vp4620/test-matrix.md
Signed-off-by: Artur Raglis <artur.raglis@3mdeb.com>
> variants/msi_z690/overview.md: update MSI mobo website

- docs/variants/msi_z690/releases.md
> docs/variants/msi_z690/releases.md: add v0.4.0 release notes

- docs/unified-test-documentation/dasharo-compatibility/303-custom-boot-menu-key.md
- mkdocs.yml
Signed-off-by: Kamil Pokornicki [kamil.pokornicki@3mdeb.com](mailto:kamil.pokornicki@3mdeb.com)
> dasharo-compatibility/303-custom-boot-menu-key.md: extension of documentation

- docs/variants/asus_kgpe_d16/releases.md
- docs/variants/clevo_nv41/releases.md
- docs/variants/msi_z690/releases.md
- docs/variants/novacustom_ns5x/releases.md
- docs/variants/protectli_fw6/releases.md
- docs/variants/protectli_vp4620/releases.md
- docs/variants/talos_2/releases.md
- docs/variants/tuxedo_ibs15/releases.md
> docs/variants/: add links to spreadsheets with test results

- docs/unified-test-documentation/dasharo-compatibility/321-docking-station-usb-c.md
- docs/unified-test-documentation/dasharo-compatibility/322-docking-station-audio.md
- docs/unified-test-documentation/dasharo-compatibility/323-docking-station-detect.md
- docs/unified-test-documentation/dasharo-compatibility/324-docking-station-usb-devices.md
- docs/variants/clevo_nv41/hardware-matrix.md
- docs/variants/clevo_nv41/test-matrix.md
- docs/variants/novacustom_ns5x/hardware-matrix.md
- docs/variants/novacustom_ns5x/test-matrix.md
- mkdocs.yml
Signed-off-by: Kamil Pokornicki [kamil.pokornicki@3mdeb.com](mailto:kamil.pokornicki@3mdeb.com)
> Docking station tests

- docs/variants/novacustom_ns5x/test-matrix.md
> docs/variants/novacustom_ns5x/test-matrix.md: add CPU frequency measure

- docs/dev-proc/smbios-rules.md
> dev-proc/smbios-rules.md: fix incorrect date

- docs/common-coreboot-docs/fwupd_usage.md
> fwupd: bump version to v1.2.0

- docs/unified-test-documentation/dasharo-compatibility/321-docking-station-usb-c.md
> dasharo-compatibility/321-docking-station-usb-c.md: update expected result

- docs/dasharo-menu-docs/overview.md
- mkdocs.yml
> docs/dasharo-menu-docs: start creating Dasharo menu docs

- docs/unified-test-documentation/dasharo-compatibility/31F-audio-subsystem.md
Signed off by Przemysław Banasiak (przemyslaw.banasiak@3mdeb.com)
> audio subsystem automation

- docs/variants/protectli_vp2410/building-manual.md
- docs/variants/protectli_vp2410/hardware-matrix.md
- docs/variants/protectli_vp2410/installation-manual.md
- docs/variants/protectli_vp2410/overview.md
- docs/variants/protectli_vp2410/releases.md
- docs/variants/protectli_vp2410/test-matrix.md
- mkdocs.yml
> docs/variants/protectli_vp2410: add documentation for VP2410

- docs/unified-test-documentation/dasharo-performance/402-cpu-frequency.md
> dasharo-performance/402-cpu-frequency.md: add test cases on Windows

- docs/variants/msi_z690/releases.md
> docs/variants/msi_z690/releases.md: add v1.0.0 release info

- docs/unified-test-documentation/dasharo-security/201-verified-boot.md
> Recovery boot popup documentation

- docs/unified-test-documentation/dasharo-compatibility/320-fwupd-firmware-update.md
- docs/unified-test-documentation/dasharo-compatibility/326-DTS-firmware-update.md
- docs/variants/novacustom_ns5x/test-matrix.md
- docs/variants/novacustom_nv4x/test-matrix.md
- mkdocs.yml
> dasharo-compatibility/326-DTS-firmware-update.md: add file

- docs/common-coreboot-docs/custom_logo.md
- docs/common-coreboot-docs/dasharo_tools_suite.md
- docs/common-coreboot-docs/fwupd_usage.md
- docs/dev-proc/source-code-structure.md
- docs/variants/asus_kgpe_d16/building-manual.md
- docs/variants/dell_optiplex/building-manual.md
- docs/variants/dell_optiplex/initial-deployment.md
- docs/variants/msi_z690/building-manual.md
- docs/variants/msi_z690/installation-manual.md
- docs/variants/msi_z690/recovery.md
- docs/variants/novacustom_ns5x/building.md
- docs/variants/novacustom_ns5x/installation.md
- docs/variants/novacustom_nv4x/building.md
- docs/variants/novacustom_nv4x/ec_update.md
- docs/variants/novacustom_nv4x/flashing_external.md
- docs/variants/novacustom_nv4x/flashing_internal.md
- docs/variants/protectli_fw6/building-manual.md
- docs/variants/protectli_vp2410/building-manual.md
- docs/variants/protectli_vp2410/installation-manual.md
- docs/variants/protectli_vp4620/building-manual.md
- docs/variants/protectli_vp4620/installation-manual.md
- docs/variants/talos_2/building-manual.md
- docs/variants/talos_2/installation-manual.md
- docs/variants/tuxedo_ibs15/building.md
- docs/variants/tuxedo_ibs15/installation.md
> docs: remove $ and # before commands

- docs/variants/msi_z690/faq.md
> msi_z690/faq.md: add section with description of problems with gpu

- docs/unified-test-documentation/dasharo-compatibility/317-usb-camera.md
> update usb camera win11 docs to automated test

- docs/unified-test-documentation/dasharo-compatibility/31K-minipcie-verification.md
> update mpcie win11 docs to automated test

- docs/variants/msi_z690/cpu-hcl.md
Adds 12700k to the cpu HCL with linked Qubes HCL
Signed-off-by: Michael Wikman <michaelwikman95@gmail.com>
> add 12700k hcl

- docs/variants/protectli_vp4620/test-matrix.md
> docs/variants/protectli_vp4620/test-matrix.md: update for v1.0.16 release

- docs/unified-test-documentation/dasharo-performance/403-device-boot-measure.md
- mkdocs.yml
> dasharo-performance/403-device-boot-measure.md: add file

- docs/unified-test-documentation/dasharo-compatibility/326-DTS-firmware-update.md
- mkdocs.yml
> dasharo-compatibility/326-DTS-firmware-update.md: add new test case

- docs/unified-test-documentation/dasharo-compatibility/31N-usb-boot.md
- docs/unified-test-documentation/dasharo-compatibility/31O-usb-detect.md
- docs/variants/asus_kgpe_d16/test-matrix.md
- docs/variants/protectli_vp4620/hardware-matrix.md
- docs/variants/protectli_vp4620/test-matrix.md
- docs/variants/talos_2/test-matrix.md
> docs/variants/protectli_vp4620/test-matrix.md: add existing test cases

- docs/unified-test-documentation/dasharo-security/20J-bios-lock-support.md
- docs/variants/protectli_vp4620/test-matrix.md
- mkdocs.yml
> dasharo-security/20J-bios-lock-support.md: add new test suite 

- docs/unified-test-documentation/dasharo-compatibility/328-me-neuter.md
- docs/unified-test-documentation/dasharo-security/20F-me-neuter.md
- docs/variants/protectli_vp4620/test-matrix.md
- mkdocs.yml
> docs/unified-test-documentation/dasharo-compatibility/328-me-neuter.md: add file

- docs/unified-test-documentation/dasharo-compatibility/315b-netboot-utilities.md
> dasharo-compatibility/315b-netboot-utilities.md: improve NBT003.001 test case

- docs/dasharo-menu-docs/overview.md
- docs/variants/novacustom_nv4x/compatibility-check-results-ubuntu.md
- mkdocs.yml
> docs/variants/novacustom_nv4x/compatibility-check-results-ubuntu.md: add file

- docs/variants/protectli_vp46xx/releases.md
> fix download link for vp4620 v1.0.16

- docs/common-coreboot-docs/vboot_signing.md
> common-coreboot-docs/vboot_signing.md: update

- docs/unified-test-documentation/dasharo-compatibility/31O-usb-detect.md
> dasharo-compatibility/31O-usb-detect.md: rename test cases

- README.md
> README.md: HW section fixes

- docs/unified-test-documentation/dasharo-performance/401-cpu-temperature.md
- docs/unified-test-documentation/dasharo-performance/402-cpu-frequency.md
> update docs for iterative cpu tests

- docs/unified-test-documentation/dasharo-performance/401-cpu-temperature.md
- docs/unified-test-documentation/dasharo-performance/402-cpu-frequency.md
Signed-off-by: sulewskiprzemyslaw <przemyslaw.sulewski@3mdeb.com>
> Performance test suites improvements

- docs/common-coreboot-docs/dasharo_tools_suite.md
Signed-off-by: Tomasz Żyjewski <tomasz.zyjewski@3mdeb.com>
> dasharo_tools_suite.md: add sha256, 3mdeb.com instead of cloud for links

- docs/unified-test-documentation/dasharo-compatibility/31P-flash-write-protection.md
- docs/variants/asus_kgpe_d16/spi-wp.md
- docs/variants/talos_2/hardware-matrix.md
> Updates during flash write protection tests

- docs/common-coreboot-docs/dasharo_tools_suite.md
> dasharo_tools_suite.md: add information about method of disabling Secure Boot

- docs/common-coreboot-docs/dasharo_tools_suite.md
> dasharo_tools_suite.md: improve linking to secure boot section

- docs/variants/dell_optiplex/building-manual.md
- docs/variants/dell_optiplex/firmware-update.md
- docs/variants/dell_optiplex/hardware-matrix.md
- docs/variants/dell_optiplex/initial-deployment.md
- docs/variants/dell_optiplex/overview.md
- docs/variants/dell_optiplex/recovery.md
- docs/variants/dell_optiplex/releases.md
> dell_optiplex: add CE status explaination

- docs/common-coreboot-docs/vboot_signing.md
- docs/unified-test-documentation/dasharo-security/20J-bios-lock-support.md
Signed-off-by: Kamil Pokornicki [[kamil.pokornicki@3mdeb.com]
> Update documentation during VP46xx release

- docs/variants/novacustom_ns5x/ec-recovery.md
> docs/variants/novacustom_ns5x/ec-recovery.md: improve linking to images

- docs/variants/novacustom_ns5x/ec-recovery.md
> docs/variants/novacustom_ns5x/ec-recovery.md: update documentation

- docs/unified-test-documentation/dasharo-compatibility/327-embedded_controller_flashing.md
- docs/variants/asus_kgpe_d16/test-matrix.md
- docs/variants/novacustom_ns5x/test-matrix.md
- mkdocs.yml
> dasharo-compatibility/327-embedded_controller_flashing.md: add file

- docs/variants/asus_kgpe_d16/hardware-matrix.md
> update kgpe hw matrix with tpm info

- docs/variants/msi_z690/memory-hcl.md
> docs/variants/msi_z690/memory-hcl.md: add mixed configuration

- docs/unified-test-documentation/dasharo-compatibility/308-debian-stable-and-ubuntu-lts-support.md
- docs/variants/asus_kgpe_d16/test-matrix.md
- docs/variants/msi_z690/test-matrix.md
- docs/variants/novacustom_ns5x/test-matrix.md
- docs/variants/novacustom_nv4x/test-matrix.md
- docs/variants/protectli_fw6/test-matrix.md
- docs/variants/protectli_vp2410/test-matrix.md
- docs/variants/protectli_vp46xx/test-matrix.md
- docs/variants/talos_2/test-matrix.md
- docs/variants/tuxedo_ibs15/test-matrix.md
> dasharo-compatibility/308-debian-stable-and-ubuntu-lts-support.md: update documentation

- docs/transparent-validation/msi-z690/assembly-and-validation.md
> docs/transparent-validation/msi-z690/assembly-and-validation.md: add steps to assembly only motherboard

- docs/unified-test-documentation/dasharo-performance/405-fan-control-measure.md
- docs/unified-test-documentation/dasharo-performance/405-fan-control.md
- docs/variants/asus_kgpe_d16/test-matrix.md
- mkdocs.yml
> add tests for fan speed

- docs/unified-test-documentation/dasharo-compatibility/327-embedded_controller_flashing.md
- docs/variants/novacustom_ns5x_7x/hardware-matrix.md
- docs/variants/novacustom_ns5x_7x/test-matrix.md
> Updates during release novacustom v1.3.0

- docs/variants/talos_2/test-matrix.md
> talos_2/test-matrix.md: add information about cpu frequency measure tests

- docs/variants/talos_2/releases.md
> docs/variants/talos_2/releases.md: change release 0.6.0 date

- docs/variants/novacustom_ns5x_7x/test-matrix.md
> docs/variants/novacustom_ns5x_7x/test-matrix.md: add test case

- docs/variants/novacustom_ns5x_7x/releases.md
> docs/variants/novacustom_ns5x_7x/releases.md: release v1.3.0

- docs/variants/novacustom_ns5x_7x/releases.md
> novacustom_ns5x_7x/releases.md: add info about ec transition

- docs/variants/asus_kgpe_d16/hardware-matrix.md
- docs/variants/asus_kgpe_d16/releases.md
Signed-off-by: Kamil Pokornicki [kamil.pokornicki@3mdeb.com](mailto:kamil.pokornicki@3mdeb.com)
> Kgpe d16 documentation update during release

- docs/variants/asus_kgpe_d16/setup.md
> docs/variants/asus_kgpe_d16/setup.md: Fix TPM section

- docs/unified-test-documentation/dasharo-compatibility/31T-cpu-status.md
> add tests for win11 cpu status

- docs/common-coreboot-docs/dumping_logs.md
- mkdocs.yml
> docs/common-coreboot-docs/dumping_logs.md: Add document

- docs/unified-test-documentation/dasharo-compatibility/301-memory-hcl.md
- docs/unified-test-documentation/dasharo-compatibility/306-usb-hid-and-msc-support.md
- docs/unified-test-documentation/dasharo-compatibility/30M-uefi-compatible-interface.md
- docs/unified-test-documentation/dasharo-compatibility/312-nvme-support.md
- docs/unified-test-documentation/dasharo-compatibility/316-sdcard-reader.md
- docs/unified-test-documentation/dasharo-compatibility/317-usb-camera.md
- docs/unified-test-documentation/dasharo-compatibility/318-m2-wifi-bluetooth.md
- docs/unified-test-documentation/dasharo-compatibility/319-nvidia-graphics.md
- docs/unified-test-documentation/dasharo-compatibility/31E-display-ports-and-lcd.md
- docs/unified-test-documentation/dasharo-compatibility/31F-audio-subsystem.md
- docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
- docs/unified-test-documentation/dasharo-compatibility/31H-usb-type-c.md
- docs/unified-test-documentation/dasharo-compatibility/31I-nvme-switching.md
- docs/unified-test-documentation/dasharo-compatibility/31J-sleep-mode.md
- docs/unified-test-documentation/dasharo-compatibility/31K-minipcie-verification.md
- docs/unified-test-documentation/dasharo-compatibility/31L-smbios.md
- docs/unified-test-documentation/dasharo-compatibility/31M-emmc-support.md
- docs/unified-test-documentation/dasharo-compatibility/31R-pcie-ports.md
- docs/unified-test-documentation/dasharo-compatibility/31W-device-tree.md
- docs/unified-test-documentation/dasharo-compatibility/320-fwupd-firmware-update.md
- docs/unified-test-documentation/dasharo-security/200-tpm-support.md
- docs/unified-test-documentation/dasharo-security/201-verified-boot.md
- docs/unified-test-documentation/dasharo-security/203-measured-boot.md
- docs/unified-test-documentation/generic-test-setup.md
- docs/variants/protectli_fw6/installation-manual.md
- docs/variants/protectli_vp2410/installation-manual.md
- docs/variants/protectli_vp46xx/initial-deployment.md
Signed-off-by: Kacper Stojek <kacper.stojek@3mdeb.com>
> Change ubuntu versions

- docs/common-coreboot-docs/vboot_signing.md
Signed-off-by: Kacper Stojek <kacper.stojek@3mdeb.com>
> Make vboot compilation utilize a docker image

- docs/unified-test-documentation/dasharo-compatibility/319-nvidia-graphics.md
> nvidia-graphics.md: improve linking to external site

- docs/variants/novacustom_nv4x/test-matrix.md
> docs/variants/novacustom_nv4x/test-matrix.md: update VBO and FAN test cases

- docs/variants/dell_optiplex/building-manual.md
- docs/variants/dell_optiplex/firmware-update.md
> variants/dell_optiplex/building-manual.md: simplify building procedure

- docs/unified-test-documentation/dasharo-compatibility/315-network-boot.md
- docs/variants/asus_kgpe_d16/test-matrix.md
- docs/variants/msi_z690/test-matrix.md
- docs/variants/novacustom_ns5x_7x/test-matrix.md
- docs/variants/novacustom_nv4x/test-matrix.md
- docs/variants/protectli_fw6/test-matrix.md
- docs/variants/protectli_vp2410/test-matrix.md
- docs/variants/tuxedo_ibs15/test-matrix.md
> dasharo-compatibility/315-network-boot.md: add and update test cases

- docs/unified-test-documentation/dasharo-compatibility/31F-audio-subsystem.md
- docs/variants/protectli_vp46xx/test-matrix.md
> dasharo-compatibility/31F-audio-subsystem.md: add new test cases

- docs/unified-test-documentation/dasharo-compatibility/326b-firmware-building-locally.md
- docs/variants/novacustom_ns5x_7x/test-matrix.md
- docs/variants/novacustom_nv4x/test-matrix.md
- mkdocs.yml
> create testing procedure for building and flashing coreboot from source

- docs/unified-test-documentation/dasharo-security/206-secure-boot.md
> dasharo-security/206-secure-boot.md: add 3 new test cases

- docs/variants/protectli_vp46xx/releases.md
> protectli_vp46xx/releases.md: add v1.0.17

- docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
- docs/variants/novacustom_ns5x_7x/post_install.md
- docs/variants/novacustom_nv4x/post_install.md
> docs/variants/novacustom_ns5x_7x/nv4x/post_install.md: add post-install step on Windows 11

- docs/unified-test-documentation/dasharo-compatibility/328-logo-customization-functionality.md
- docs/variants/novacustom_ns5x_7x/test-matrix.md
- docs/variants/novacustom_nv4x/test-matrix.md
- mkdocs.yml
> add test cases for custom logo

- docs/unified-test-documentation/dasharo-compatibility/326b-firmware-building-locally.md
- docs/unified-test-documentation/dasharo-security/201-verified-boot.md
- docs/variants/asus_kgpe_d16/test-matrix.md
- docs/variants/msi_z690/test-matrix.md
- docs/variants/novacustom_ns5x_7x/test-matrix.md
- docs/variants/novacustom_nv4x/test-matrix.md
- docs/variants/protectli_vp46xx/test-matrix.md
- docs/variants/tuxedo_ibs15/test-matrix.md
> add tests for vboot key generation and firmware signing

- docs/variants/msi_z690/recovery.md
- docs/variants/novacustom_ns5x_7x/test-matrix.md
- docs/variants/novacustom_ns5x_7x_12th_gen/test-matrix.md
- docs/variants/novacustom_nv4x/test-matrix.md
- docs/variants/novacustom_nv4x_12th_gen/test-matrix.md
- mkdocs.yml
> /docs/variants/: add test matrixes for NovaCustom 12th gen products

- docs/unified-test-documentation/dasharo-security/20J-bios-lock-support.md
> add bios lock support deactiavtion test doc

- docs/unified-test-documentation/dasharo-security/203-measured-boot.md
> dasharo-security/203-measured-boot.md: update test module

- docs/variants/novacustom_ns5x_7x/building-manual.md
- docs/variants/novacustom_nv4x/building.md
> novacustom: add EC build doc

- docs/variants/msi_z690/cpu-hcl.md
- docs/variants/msi_z690/faq.md
- docs/variants/msi_z690/gpu-hcl.md
Plus remove an outdated note in faq.md, since PCIe is now supported.
> Add HCL entries for my tested config

- docs/variants/novacustom_nv4x/post_install.md
> docs/variants/novacustom_nv4x/post_install.md: add Nvidia drivers section

- docs/common-coreboot-docs/dasharo_tools_suite.md
Signed-off-by: Tomasz Żyjewski <tomasz.zyjewski@3mdeb.com>
> DTS - update ec transition section

- docs/variants/novacustom_ns5x_7x/post_install.md
- docs/variants/novacustom_ns5x_7x_12th_gen/post_install.md
> ns5x: add DIPM tweak for Windows and Linux

- docs/variants/talos_2/hardware-matrix.md
> add nvme to talos hw matrix

- docs/variants/protectli_vp46xx/hardware-matrix.md
- docs/variants/protectli_vp46xx/test-matrix.md
> Protectli VP4650 documentation

- docs/variants/novacustom_ns5x_7x/building-manual.md
- docs/variants/novacustom_nv4x/building-manual.md
> ns5x, nv4x: update building instructions for v1.3.0

- docs/common-coreboot-docs/dasharo_tools_suite.md
> docs/common-coreboot-docs/dasharo_tools_suite.md: update changelog dts 1.0.2

- docs/index.md
- docs/variants/msi_z690/faq.md
- docs/variants/msi_z690/hardware-matrix.md
- docs/variants/msi_z690/test-matrix.md
- docs/variants/novacustom_nv4x/initial-deployment.md
- docs/variants/novacustom_nv4x/overview.md
- mkdocs.yml
Signed-off-by: sulewskiprzemyslaw <przemyslaw.sulewski@3mdeb.com>
> docs/variants/msi_z690/: add MSI Z690-A DDR5 to test and HW matrixes

- docs/common-coreboot-docs/dasharo_tools_suite.md
- docs/glossary.md
- docs/osf-trivia-list/dts.md
- docs/variants/dell_optiplex/initial-deployment.md
- mkdocs.yml
> introduce concept of DTS SE

- docs/transparent-validation/msi-z690/assembly-and-validation.md
- docs/unified-test-documentation/dasharo-compatibility/31U-heads-bootloader-support.md
- docs/variants/msi_z690/community-test-results.md
- docs/variants/msi_z690/development.md
- docs/variants/msi_z690/faq.md
- docs/variants/msi_z690/firmware-update.md
- docs/variants/msi_z690/initial-deployment.md
- docs/variants/msi_z690/overview.md
- docs/variants/msi_z690/recovery.md
- mkdocs.yml
> docs/variants/msi_z690/: add missing parts of documentation MSI

- docs/variants/msi_z690/memory-hcl.md
> create HCL compatibility results for MSI z690 ddr5

- docs/variants/novacustom_ns5x_7x_12th_gen/test-matrix.md
> docs/variants/novacustom_ns5x_7x_12th_gen/test-matrix.md: update file

- docs/unified-test-documentation/dasharo-security/206-secure-boot.md
- docs/variants/novacustom_ns5x_7x/test-matrix.md
- docs/variants/novacustom_ns5x_7x_12th_gen/test-matrix.md
- docs/variants/novacustom_nv4x/test-matrix.md
- docs/variants/novacustom_nv4x_12th_gen/test-matrix.md
- docs/variants/protectli_vp46xx/test-matrix.md
- docs/variants/tuxedo_ibs15/test-matrix.md
> dasharo-security/206-secure-boot.md: add new 3 test cases

- docs/unified-test-documentation/dasharo-security/20F-me-neuter.md
- docs/variants/protectli_vp46xx/test-matrix.md
> dasharo-security/20F-me-neuter.md: add and update test cases

- docs/unified-test-documentation/dasharo-security/200-tpm-support.md
> dasharo-security/200-tpm-support.md: update test module and add 2 new test cases

- docs/unified-test-documentation/dasharo-compatibility/328-logo-customization-functionality.md
- docs/variants/novacustom_ns5x_7x_12th_gen/test-matrix.md
- docs/variants/novacustom_nv4x_12th_gen/test-matrix.md
> Logo customization: update test case and test matixes

- docs/dasharo-tools-suite/documentation.md
- docs/dasharo-tools-suite/releases.md
Signed-off-by: Tomasz Żyjewski <tomasz.zyjewski@3mdeb.com>
> dasharo-tools-suite: fix couple naming typos

- docs/variants/novacustom_nv4x_12th_gen/test-matrix.md
> docs/variants/novacustom_nv4x_12th_gen/test-matrix.md: update test cases

- docs/variants/novacustom_ns5x_adl/hardware-matrix.md
> docs/variants/novacustom_ns5x_adl/hardware-matrix.md: update file

- docs/variants/msi_z690/cpu-hcl.md
- docs/variants/msi_z690/gpu-hcl.md
- docs/variants/msi_z690/openness_analysis.md
> docs/variants/msi_z690/: rendering improvements

- docs/variants/novacustom_ns5x_adl/hardware-matrix.md
- docs/variants/novacustom_nv4x_adl/hardware-matrix.md
- docs/variants/novacustom_nv4x_tgl/hardware-matrix.md
> docs/variants/novacustom_nv4x_adl/hardware-matrix.md: add file content

- docs/variants/talos_2/hardware-matrix.md
> talos_2/hardware-matrix.md: improve ssd declaration in matrix

- docs/variants/dell_optiplex/initial-deployment.md
- docs/variants/dell_optiplex/releases.md
Signed-off-by: XorFlag <services@lunicore.io>
Added 9010 MT to docs. DTS flash was functional and no issues were found at boot.
> add 9010 MT

- docs/unified/clevo/post-install.md
> docs/unified/clevo/post-install.md: add nv4x adl verbs fix

- docs/unified-test-documentation/dasharo-compatibility/31U-heads-bootloader-support.md
> dasharo-compatibility/31U-heads-bootloader-support.md: add test case

- docs/variants/protectli_vp46xx/building-manual.md
- docs/variants/protectli_vp46xx/firmware-update.md
- docs/variants/protectli_vp46xx/initial-deployment.md
- docs/variants/protectli_vp46xx/overview.md
- docs/variants/protectli_vp46xx/releases.md
- docs/variants/protectli_vp46xx/test-matrix.md
> docs/variants/protectli_vp46xx: update documentation

- .conform.yaml
- .gitignore
- README.md
> README.md: improve contribution guide

- docs/unified-test-documentation/dasharo-compatibility/31U-heads-bootloader-support.md
> dasharo-compatibility/31U-heads-bootloader-support.md: add new 7 test cases

- docs/variants/msi_z690/faq.md
> docs/variants/msi_z690/faq.md: update answer for question about compatibility

- docs/variants/msi_z690/releases.md
> docs/variants/msi_z690/releases.md: add v1.1.0 release notes

- docs/variants/msi_z690/faq.md
> docs/variants/msi_z690/faq.md: add question about platform name nomenclature

- docs/variants/talos_2/test-matrix.md
> update test matrix

- docs/unified-test-documentation/dasharo-compatibility/31U-heads-bootloader-support.md
> dasharo-compatibility/31U-heads-bootloader-support.md: add new test cases related to GPG keys

- docs/unified-test-documentation/dasharo-compatibility/31U-heads-bootloader-support.md
- docs/unified-test-documentation/dasharo-security/200-tpm-support.md
- docs/variants/asus_kgpe_d16/test-matrix.md
- docs/variants/dell_optiplex/test-matrix.md
- docs/variants/msi_z690/test-matrix.md
- docs/variants/novacustom_ns5x_adl/test-matrix.md
- docs/variants/novacustom_ns5x_tgl/test-matrix.md
- docs/variants/novacustom_nv4x_adl/test-matrix.md
- docs/variants/novacustom_nv4x_tgl/test-matrix.md
- docs/variants/protectli_vp2410/test-matrix.md
- docs/variants/protectli_vp46xx/test-matrix.md
- docs/variants/talos_2/test-matrix.md
- docs/variants/tuxedo_ibs15/test-matrix.md
> dasharo-security/200-tpm-support.md: add test cases performed on Heads

- docs/variants/msi_z690/memory-hcl.md
> docs/variants/msi_z690/memory-hcl.md: add new RAM module DDR5

- docs/unified-test-documentation/dasharo-compatibility/309-qubesos-stable-support.md
- docs/unified-test-documentation/dasharo-compatibility/309-qubesos-support.md
- docs/variants/novacustom_ns5x_adl/test-matrix.md
- docs/variants/novacustom_ns5x_tgl/test-matrix.md
- docs/variants/novacustom_nv4x_adl/test-matrix.md
- docs/variants/novacustom_nv4x_tgl/test-matrix.md
- mkdocs.yml
> create test for qubes os installation and boot

- docs/unified-test-documentation/dasharo-compatibility/310-fedora-support.md
- docs/variants/novacustom_ns5x_adl/test-matrix.md
- docs/variants/novacustom_ns5x_tgl/test-matrix.md
- docs/variants/novacustom_nv4x_adl/test-matrix.md
- docs/variants/novacustom_nv4x_tgl/test-matrix.md
- mkdocs.yml
> dasharo-compatibility/310-fedora-support.md: add file

- docs/variants/novacustom_ns5x_adl/test-matrix.md
- docs/variants/novacustom_ns5x_tgl/test-matrix.md
- docs/variants/novacustom_nv4x_adl/test-matrix.md
- docs/variants/novacustom_nv4x_tgl/test-matrix.md
> docs/variants/novacustom_n*/test-matrix.md: add new DDP test module

- docs/unified-test-documentation/dasharo-compatibility/340-docking-station-net-interface.md
- docs/variants/novacustom_ns5x_adl/test-matrix.md
- docs/variants/novacustom_ns5x_tgl/test-matrix.md
- docs/variants/novacustom_nv4x_adl/test-matrix.md
- docs/variants/novacustom_nv4x_tgl/test-matrix.md
- mkdocs.yml
> create tests for docking station net interface

- docs/common-coreboot-docs/dumping_logs.md
- docs/osf-trivia-list/deployment.md
- docs/unified-test-documentation/dasharo-compatibility/315-network-boot.md
- docs/unified-test-documentation/dasharo-compatibility/326-dasharo-tools-suite.md
- docs/variants/msi_z690/recovery.md
- docs/variants/novacustom_ns5x_adl/releases.md
- docs/variants/novacustom_ns5x_tgl/releases.md
- docs/variants/novacustom_nv4x_tgl/releases.md
- mkdocs.yml
- requirements.txt
> mkdocs.yml: add test redirection

- docs/unified-test-documentation/dasharo-compatibility/340-docking-station-net-interface.md
- mkdocs.yml
> Minor correction of NET Interface test module

- docs/dev-proc/documentation-guidelines.md
- mkdocs.yml
> Docs guidelines

- docs/variants/protectli_vp46xx/releases.md
> docs/variants/protectli_vp46xx/releases.md: fix links to FSPs

- docs/variants/protectli_vp46xx/hardware-matrix.md
> docs/variants/protectli_vp46xx/hardware-matrix.md: add protectli tpm to hw matrix

- docs/unified-test-documentation/dasharo-compatibility/324-docking-station-usb-devices.md
> dasharo-compatibility/324-docking-station-usb-devices.md: add 2 new test cases

- docs/unified-test-documentation/dasharo-compatibility/306-usb-hid-and-msc-support.md
- docs/variants/protectli_fw6/test-matrix.md
- docs/variants/talos_2/test-matrix.md
> dasharo-compatibility/306-usb-hid-and-msc-support.md: add 2 new test cases

- docs/variants/protectli_vp46xx/releases.md
> docs/variants/protectli_vp46xx/releases.md: add v1.0.19 release

- docs/dasharo-tools-suite/documentation.md
- mkdocs.yml
> Add redirection and update dead links

- docs/variants/protectli_vp46xx/firmware-update.md
> protectli_vp46xx/firmware-update.md: add information about versions newer than 1.0.18

- mkdocs.yml
> mkdocs.yml: add nav to initial deployment docs for vp24 platforms

- docs/variants/msi_z690/gpu-hcl.md
> docs/variants/msi_z690/gpu-hcl.md: add miczyg's GPUs

- docs/variants/dell_optiplex/test-matrix.md
> docs/variants/dell_optiplex/test-matrix.md: remove incorrect reference to another product

- docs/variants/novacustom_ns5x_adl/test-matrix.md
- docs/variants/novacustom_nv4x_adl/test-matrix.md
> docs/variants/novacustom: add me neutering to the test scope for ADL laptops

- docs/unified-test-documentation/dasharo-security/20F-me-neuter.md
> dasharo-security/20F-me-neuter.md: add PCIe 5.0 firmware caching case

- docs/unified-test-documentation/dasharo-security/200-tpm-support.md
> dasharo-security/200-tpm-support.md: add PPI tests

- docs/unified-test-documentation/dasharo-security/20L-early-boot-dma-protection.md
- mkdocs.yml
> dasharo-security/20L-early-boot-dma-protection.md: add test case

- docs/unified-test-documentation/dasharo-security/200-tpm-support.md
> docs/unified-test-documentation/dasharo-security/200-tpm-support.md: add new tests

- docs/transparent-validation/rte/v1.1.0/flashing-guide.md
> transparent-validation/rte/v1.1.0/flashing-guide.md: fix links and table content

- docs/unified-test-documentation/dasharo-security/200-tpm-support.md
> create object tests for tpm2

- docs/unified-test-documentation/dasharo-security/200-tpm-support.md
> add tpm pcr operation tests

- docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> add tests for keyboard illumination

- docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> create tests for fnlock functionality

- docs/variants/protectli_vp2420/hardware-matrix.md
> docs/variants/protectli_vp2420/hardware-matrix.md: mix linguistic error

- docs/dasharo-tools-suite/documentation.md
Simple instruction on how to send autoboot script from iPXE shell by using DTS
> Autoboot scripts from iPXE shell

- docs/projects/trenchboot-aem-v2.md
- docs/projects/trenchboot-aem.md
- mkdocs.yml
> projects/trenchboo-aem: add v2

- docs/unified-test-documentation/dasharo-compatibility/306-usb-hid-and-msc-support.md
- docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
- docs/variants/dell_optiplex/test-matrix.md
- docs/variants/novacustom_ns5x_adl/test-matrix.md
- docs/variants/novacustom_ns5x_tgl/test-matrix.md
- docs/variants/novacustom_nv4x_adl/test-matrix.md
- docs/variants/novacustom_nv4x_tgl/test-matrix.md
- docs/variants/protectli_fw6/test-matrix.md
- docs/variants/protectli_vp2410/test-matrix.md
- docs/variants/protectli_vp2420/test-matrix.md
- docs/variants/protectli_vp46xx/test-matrix.md
- docs/variants/talos_2/test-matrix.md
- docs/variants/tuxedo_ibs15/test-matrix.md
> create tests for USB configuration in firmware

- docs/common-coreboot-docs/dumping_logs.md
> docs/common-coreboot-docs/dumping_logs.md: extend the document

- .markdownlint.yaml
- docs/unified-test-documentation/dasharo-compatibility/315-network-boot.md
- docs/variants/dell_optiplex/test-matrix.md
- docs/variants/msi_z690/test-matrix.md
- docs/variants/novacustom_ns5x_tgl/test-matrix.md
- docs/variants/novacustom_nv4x_adl/test-matrix.md
- docs/variants/novacustom_nv4x_tgl/test-matrix.md
- docs/variants/protectli_fw6/test-matrix.md
- docs/variants/tuxedo_ibs15/test-matrix.md
> add tests for network boot disable/enable

- docs/variants/msi_z690/initial-deployment.md
Wrong motherboard model was listed, just a simple typo correction.
> fixed typo

- docs/variants/msi_z690/recovery.md
The intro paragraph contained a few grammar issues, including an unnecessary complex sentence structure ("It may happen that...") and unconventional pronoun usage ("install back").
> docs/variants/msi_z690/recovery.md: fix grammar issues

- docs/variants/msi_z690/memory-hcl.md
Added missing article, made capitalization scheme consistent, and corrected verb tense.
> fixed grammar

- docs/unified-test-documentation/dasharo-security/20L-early-boot-dma-protection.md
- docs/variants/msi_z690/test-matrix.md
> create tests for early boot

- docs/variants/msi_z690/recovery.md
Thanks for your patience and help while I'm learning how to use git and pre-commit.
> docs/variants/msi_z690/recovery.md: edit intro

- docs/variants/protectli_vp2420/test-matrix.md
- docs/variants/protectli_vp46xx/test-matrix.md
> VP2420 test matrix expand

- docs/variants/protectli_vp2420/test-matrix.md
> docs/variants/protectli_vp2420/test-matrix.md: improve note

- docs/variants/msi_z690/test-matrix.md
> docs/variants/msi_z690/test-matrix.md: update test matrix; expand verified boot

- docs/dasharo-menu-docs/dasharo-system-features.md
Add info about boot menu option to documentation
> dasharo-system-features.md: add boot menu option

- docs/unified-test-documentation/dasharo-compatibility/304-custom-logo.md
> dasharo-compatibility/304-custom-logo.md: improve expected result section

- docs/dasharo-tools-suite/documentation.md
Add link to github issue as there are some problems with that functionality
> Add note about ipxe commands functionality

- docs/variants/protectli_vp46xx/hardware-matrix.md
> docs/variants/protectli_vp46xx/hardware-matrix.md: update list of power supplies

- docs/variants/talos_2/hardware-matrix.md
> docs/variants/talos_2/hardware-matrix.md: add second CPU to the hw matrix

- docs/unified-test-documentation/dasharo-security/207-boot-guard-support.md
- mkdocs.yml
> Bootguard test documentation

- docs/unified-test-documentation/dasharo-compatibility/356-docking-station-sd-card-reader.md
- docs/variants/novacustom_ns5x_adl/test-matrix.md
- docs/variants/novacustom_ns5x_tgl/test-matrix.md
- docs/variants/novacustom_nv4x_adl/test-matrix.md
- docs/variants/novacustom_nv4x_tgl/test-matrix.md
- mkdocs.yml
Test documentation regarding SD card reader built into the docking station.
> Add 356-docking-station-sd-card-reader.md

- docs/dev-proc/source-code-structure.md
Actually render the unordered list as such.
> docs/dev-proc/source-code-structure/#force-push-rules: fix formatting

- docs/unified/novacustom/building-manual.md
The consequences of the warning have initially been unclear to me. Thank you @miczyg1 for providing guidance in `#dasharo-support:matrix.org`. Add this to the docs for clarification.
> docs/unified/novacustom/building_manual.md: comment on warning when building without IFD

- docs/variants/protectli_ptx01/hardware-matrix.md
- docs/variants/protectli_ptx01/test-matrix.md
- mkdocs.yml
> Protectli PTx01 test & hardware matrix

- mkdocs.yml
- requirements.txt
Update mkdocs and mkdocs-material in order to enable the new annotations feature.
> bump mkdocs, mkdocs-material and enable annotations

- docs/variants/protectli_vp46xx/building-manual.md
I guess this should remain a draft until v1.1.0 is released
> variants/protectli_vp46xx: update for single binary

- mkdocs.yml
fixe broken links caused by #651
> mkdocs.yml: correct link to test 359

- docs/unified/msi/hcl.md
Can confirm that with my GPU I can access the setup menu. PCI id is `1002:731f` - reference model 5700 XT.
> Add another HCL entry for MSI

- docs/variants/supermicro_x11_lga1151_series/overview.md
Small fix, but just something I noticed when reading the docs.
Thanks for the amazing documentation :)
> Fixed contact us typo in supermicro_x11_lga1151_series

- mkdocs.yml
mkdocs reference: https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions-edit-this-page
> mkdocs.yml: add edit and source buttons

- docs/unified/clevo/post-install.md
also fix incorrect placement of some sections
> clevo/post-install.md: add TBT driver instructions

- docs/dasharo-tools-suite/releases.md
* Make it more clear that latest release are available on GH Release tab
* Remove newsletter button, as we do not use newsletter for DTS
> docs: dts: releases: add more visible info about latest release

- docs/unified/clevo/post-install.md
Add a fix for an issue where the GPU refuses to enter D3Cold causing high power draw and no s0ix residency.
> Nvidia rtd3 fix

- docs/unified/msi/recovery.md
> docs/unified/msi/recovery.md: Add note about flashrom versions

- docs/unified-test-documentation/dasharo-security/206-secure-boot.md
Add following tests: SBO009.001, SBO010.001, SBO010.002, SBO010.003, SBO010.004, SBO010.005, SBO010.006, SBO011.001, SBO012.001, SBO013.001, SBO013.002, SBO014.001, SBO015.001.
> Add new secure boot tests

- docs/guides/firmware-reflash.md
- mkdocs.yml
Simple and generic. Of course sometimes the commands may be different depending on mainboard, version, branch etc, but this guide should cover most cases.
> docs/guides/firmware-reflash.md: add flashing guide

- docs/variants/protectli_vp46xx/overview.md
- docs/variants/protectli_vp46xx/post-install.md
Signed-off-by: Piotr Kubaj <piotr.kubaj@3mdeb.com>
> docs/variants/protectli_vp46xx: document ath10k firmware issue

- docs/variants/pc_engines/hardware-matrix.md
Exact specs for user-pluggable components like Wifi card, SSD and pendrives are to be done.
> Add APU{2,3,6} to hardware matrix

- docs/osf-trivia-list/dasharo-entry-subscription.md
- mkdocs.yml
This commit introduces a new FAQ document for Dasharo Entry Subscription under the FAQ section. It provides detailed steps on how to download the Dasharo Entry Subscription binaries.
Additionally, a typo in the mkdocs.yml file is corrected from 'Checbox results' to 'Checkbox results'.
> Add Dasharo Entry Subscription FAQ and fix typo in mkdocs.yml

- docs/transparent-validation/ec-debugger/uart-relay.md
- mkdocs.yml
Add documentation for configuring and using https://github.com/Dasharo/zephyr-i2c-to-uart
> transparent-validation/ec-debugger/uart-relay.md: add doc

- docs/dasharo-tools-suite/documentation.md
- docs/unified/novacustom/firmware-update.md
Fixes: https://github.com/Dasharo/dasharo-issues/issues/253
> Remove "Disable Secure Boot" section in dts documentation

- docs/transparent-validation/msi-z690/laboratory-assembly-guide.md
- docs/transparent-validation/msi-z790/laboratory-assembly-guide.md
- docs/transparent-validation/novacustom/laboratory-assembly-guide.md
- docs/transparent-validation/protectli/laboratory-assembly-guide.md
- docs/unified-test-documentation/dasharo-performance/406-custom-fan-curve.md
- docs/variants/novacustom_ns5x_adl/releases.md
- docs/variants/novacustom_ns5x_tgl/releases.md
- docs/variants/novacustom_nv4x_adl/releases.md
- docs/variants/novacustom_nv4x_tgl/releases.md
- docs/variants/qemu_q35/releases.md
Signed-off-by: Piotr Kubaj <piotr.kubaj@3mdeb.com>
> laboratory-assembly-guide: require all USB ports to be plugged

- docs/dasharo-menu-docs/overview.md
https://github.com/Dasharo/edk2/pull/152
> overview.md: Update to a modern password policy

- docs/kb/edk2-capsule-updates.md
- mkdocs.yml
This provides some background information about capsules and their use in EDK2.
> kb/edk2-capsule-updates.md: add

- docs/unified/novacustom/features.md
Say more specifically that the battery is not used when connected to a power adapter
> docs/unified/novacustom/features.md: Improve power modes

- docs/newcomers.md
paragraphs
Pre-commit fails due to a misspelled word in a hyperlink
> docs/newcomers.md: Added Dasharo lab user guide and troubleshooting

- docs/dasharo-tools-suite/documentation.md
link to FAQ explaining how to load DPP keys.
> DTS add odroid support in documentation

- docs/variants/msi_z790/releases.md
updated ddr version of msi_Z790/releases.md to be accurate with device in testing
> msi_z790/releases.md: update ddr version

- docs/unified-test-documentation/dasharo-compatibility/328-logo-customization-functionality.md
> 328-logo-customization-functionality.md: changed key to enter shell in

- docs/unified/novacustom/firmware-update.md
This change fixes the links 404ing.
> unified/novacustom/firmware-update.md: make DTS doc links relative

- docs/unified-test-documentation/dasharo-compatibility/31F-audio-subsystem.md
Fixes https://github.com/Dasharo/open-source-firmware-validation/issues/534
> dasharo-compatibility/31F-audio-subsystem.md: add warning

- docs/kb/capsule-updates-configs.md
As in: https://github.com/Dasharo/docs/pull/946#discussion_r1856589183
> Change Relase rc number to 0x80, from 0xFF

- docs/unified-test-documentation/dasharo-compatibility/build-on-new-os.md
- mkdocs.yml
This test aims to verify that Dasharo is possible to be built using instructions from docs.dasharo.com and works properly.
> Build on a Newly Installed OS test suite

- .pre-commit-config.yaml
- mkdocs.yml
Change the navigation bar titles in the test specification to match the Dasharo Test & Feature matrix. Append test ID to them to easily distinguish them and sort the entries alphabetically.
> Improve test documentation navbar

- docs/dasharo-tools-suite/documentation/features.md
- docs/osf-trivia-list/dts.md
Shouldn't be merged before releasing current changes in DTS (in 2.2.0 milestone): https://github.com/Dasharo/dasharo-issues/issues/1165
> docs: dts: remove verbose mode, update dts log/diagnose trivia

- docs/dasharo-tools-suite/documentation/features.md
- docs/osf-trivia-list/dts.md
> Revert "docs: dts: remove verbose mode, update dts log/diagnose trivia"

- docs/osf-trolling-list/build_process.md
- docs/variants/protectli_vp2410/releases.md
Added an explanation to address [this](https://github.com/Dasharo/dasharo-issues/issues/1110) issue. Explanation was added to FAQ > Firmware build process. I am not sure if this is the best place, or we should rather add it to Guides > Verifying signatures. Maybe just a mention in the guide will be enough.
> Mention the diffrence between dev_signed and regular binaries

- docs/unified/novacustom/building-manual.md
- docs/unified/novacustom/overview.md
- docs/variants/novacustom_v540tu/releases_heads.md
- mkdocs.yml
> Novacustom v540tu

- docs/unified-test-documentation/dasharo-compatibility/31E-display-ports-and-lcd.md
- docs/unified-test-documentation/dasharo-compatibility/31F-audio-subsystem.md
- docs/unified/protectli/test-matrix.md
- docs/variants/hardkernel_odroid_h4/test-matrix.md
- docs/variants/msi_z690/test-matrix.md
- docs/variants/msi_z790/test-matrix.md
- docs/variants/novacustom_ns5x_adl/test-matrix.md
- docs/variants/novacustom_ns5x_tgl/test-matrix.md
- docs/variants/novacustom_nv4x_adl/test-matrix.md
- docs/variants/novacustom_nv4x_tgl/test-matrix.md
- docs/variants/tuxedo_ibs15/test-matrix.md
Removing discrepancies between test IDs found during vp2430 rc4 testing
> Removing discrepancies between test IDs and other corrections

- docs/unified-test-documentation/dasharo-compatibility/350-usb-a-and-c-always-on-ports.md
- docs/unified/protectli/os-installation.md
- mkdocs.yml
Test suite verifying "USB power and charging" setup menu option.
> Dasharo Compatibility: USB A and C Always on ports test suite specification

- docs/dev-proc/source-code-structure.md
This has been agreed on a meeting of 7th Feb 2025 and agreed by:
- Beata Skierka
- Krystian Hebel
- Maciej Pijanowski
- Michał Żygowski
- Michał Kopeć
- Piotr Król
> docs/dev-proc/source-code-structure.md: add commit guidelines

- docs/variants/dell_optiplex/releases.md
- docs/variants/msi_z690/releases_heads.md
- docs/variants/msi_z790/releases.md
- docs/variants/msi_z790/releases_heads.md
- docs/variants/novacustom_ns5x_adl/releases.md
- docs/variants/novacustom_ns5x_tgl/releases.md
- docs/variants/novacustom_nv4x_adl/releases.md
- docs/variants/novacustom_nv4x_adl/releases_heads.md
- docs/variants/novacustom_nv4x_tgl/releases.md
- docs/variants/novacustom_v560tu/releases_heads.md
- docs/variants/pc_engines/releases_seabios.md
- docs/variants/protectli_fw6/releases.md
- docs/variants/protectli_v1000-series/releases.md
- docs/variants/protectli_vp2410/releases.md
- docs/variants/protectli_vp46xx/releases.md
* remove fixed/changed from initial releases
* add Dasharo features info to empty initial releases
> Relnotes cleanup

- docs/unified/clevo/post-install.md
With link to Intel download site.
> clevo/post-install.md: NUC BOX ethernet driver info for Win 11

- docs/glossary.md
- docs/unified/novacustom/features.md
> Document Dasharo TrustRoot in general and for NovaCustom
