docs/variants/clevo_nv41/fwupd_usage.md
- Add missing unzip command
- Install all packages in a single command to resolve dependencies
=> docs/variants/clevo_nv41/fwupd_usage.md: fix fwupd installation instructions

docs/variants/novacustom_nv4x/flashing_external.md
Use an external flash layout file, so that building custom flashrom just for external flashing isn't needed anymore.
=> variants/novacustom_nv4x/flashing_external.md: use external layout file

docs/osf-trivia-list/me.md
The "Why is this possible" section describes ME Neutering, not soft-disabling.
Move it to the correct place in the document.
=> docs/osf-trivia-list/me.md: move 'why is this possible' to correct spot

docs/variants/talos_2/hardware-matrix.md
=> talos_2/hardware-matrix.md: add attached usb keyboard to hw matrix

docs/variants/msi_z690/recovery.md
Per the Dasharo [documentation guidelines](https://docs.dasharo.com/dev-proc/documentation-guidelines/) the most important information should be at the top of the documentation. Since flashing with the MSI Flash BIOS Button does not currently work, I moved it to the bottom. Let me know what you think.
=> docs/variants/msi_z690/recovery.md: paragraph order

docs/dasharo-tools-suite/documentation.md, docs/dasharo-tools-suite/overview.md, docs/dasharo-tools-suite/releases.md
This PR was started to make some cleanups and formatting for next release (v1.1.1)
TODO:
Signed-off-by: Tomasz Żyjewski <tomasz.zyjewski@3mdeb.com>
=> dasharo-tools-suite: documentation formatting and v1.1.1 release

docs/dasharo-tools-suite/documentation.md
Thank you @miczyg1 in `#dasharo-support:matrix.org` for clarification on the `flashrom` warning/notification.
I am not certain if the flashrom warning
```text
Setting BIOS Control at 0xdc from 0x8b to 0x89 failed.
New vaule is 0x8b.
```
is only applicable to my device, which is NV40 TGL, or if it is more general. In the former case that should perhaps be clarified in the docs as well.
Furthermore, I'm not sure how a local update of the EC firmware would be done (in line with the a local BIOS update as described here). In case I happen to investigate this in the future, I will add it.
=> docs/dasharo-tools-suite/documentation.md: add local fw update subsection & notes about warnings

docs/unified-test-documentation/dasharo-performance/401-cpu-temperature.md
Simply state that the temperature should not be higher than the DUT specification says.
=> dasharo-performance/401-cpu-temperature.md: remove obesolete sentence

docs/unified/msi/recovery.md
WSON8 exists in 8x6 and 6x5mm packages.  
Part number on the image of the BIOS flash IC ![](https://docs.dasharo.com/images/ch341a_rec/msi_flash.jpg) is 25q256jweq, as per [datasheet](https://eu.mouser.com/datasheet/2/949/w25q256jw_spi_revd_09042018-1489579.pdf) page 93 that is an 8-pad WSON 8x6mm.
Or are there MSI boards that use the smaller 6x5mm package?
=> MSI recovery.md WSON8 probe specify 8x6mm

.pre-commit-config.yaml, README.md
With the documentation we had, only commit-msg hooks were installed. What is more, we had the stages assigned wrong for specific checks (by default, each hook was assigned to each stage, so also to commit-msg).
As a result, this would result in pre-commit (in fact: commit-msg) checks to appear as if they would PASS, even if they were supposed to FAIL (and were failing in CI). In fact, most of the pre-commit hooks on files were never executed.
Refer to the pre-commit config and default values: https://pre-commit.com/#pre-commit-configyaml---top-level
=> fix pre-commit hooks intallation

.lycheeignore, docs/variants/qemu_q35/building-manual.md
Otherwise, we return with error:
Cloning into 'edk2-platforms'...
fatal: Remote branch 3323ed481d35096fb6a7eae7b49f35eff00f86cf not found in upstream origin
=> variants/qemu_q35/building-manual.md: fix cloninc edk2-platforms

docs/unified/msi/faq.md
Since 1.0 is out for 1 1/2 years, this can safely be removed, I assume. 
This corrects several grammar-related mistakes, guided by a software grammar checker.
=> Remove outdated warning

docs/unified/msi/hcl.md
"Bandwidth" here refers to video memory bandwidth, not the PCIe link width.
=> msi/hcl: fix 1080ti bandwith value

docs/dasharo-menu-docs/device-manager.md
add latest certs from https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-secure-boot-key-creation-and-management-guidance
=> dasharo-menu-docs/device-manager.md: update to include MS 2023 SB certs

docs/dasharo-tools-suite/documentation.md
Explained what "/dev/sdX" means.
Me not knowing what disk numbering means, I flashed the image to partition instead of disk, so it slowed me down for some time until I found out why it does not boot. This note would have helped me to save time, so it may help someone else.
=> Expand notes about flashing USB disk image with dd

docs/dasharo-tools-suite/releases.md
This PR does two things:
* comments out all the earlier releases, so that they aren't visible on the page
* makes the `Latest release` section bold, so that users have no choice but to go to the releases page and download the latest version
=> docs/dasharo-tools-suite/releases.md: hide earlier releases

docs/dasharo-tools-suite/documentation.md
This script adds info on how to boot dts through iPXE while also executing a custom user script at the end.
This can be done with the `local-ipxe-server.sh` script added in [this pr](https://github.com/Dasharo/meta-dts/pull/96) in `meta-dts`
This is related to [this issue](https://github.com/Dasharo/dasharo-issues/issues/387)
=> docs/dasharo-tools-suite/documentation.md: add info about ipxe boot

docs/variants/protectli_vp46xx/overview.md
This commit clarifies that we support both v1 and v2 of VP4650 and
VP4670.
Signed-off-by: Piotr Kubaj <piotr.kubaj@3mdeb.com>
=> docs/variants/protectli_vp46xx/overview.md: mention both CPU versions

docs/variants/dell_optiplex/recovery.md
[By default RTE with version above v1.1.0 uses 1.8V on the SPI VCC](https://docs.dasharo.com/transparent-validation/rte/v1.1.0/specification/#specification). It should be specified what voltage to use on the VCC pin.
=> docs/docs/variants/dell_optiplex/recovery.md: added voltage info to VCC

docs/unified-test-documentation/dasharo-compatibility/319-nvidia-graphics.md
Related to https://github.com/Dasharo/open-source-firmware-validation/pull/467
- The output does not necessarily need to be one line, if there is an nvidia audio device, for example, the output will be longer
- The text implies that only the name of a device is sufficient but one may think it needs to contain the "3D controller" so another example may solve any misunderstandings
=> unified-test-documentation/nvidia-graphics: VGA Controller is pass

docs/variants/dell_optiplex/building-manual.md
The full tag is
coreboot/coreboot-sdk:2023-11-24_2731fa619b
not what was in docs
coreboot/coreboot-sdk:2023-11-24_2731fa619
=> docker hub tag in building-manual.md was missing last letter

docs/variants/protectli_vp2410/overview.md, docs/variants/protectli_vp2420/overview.md, docs/variants/protectli_vp46xx/overview.md, docs/variants/protectli_vp46xx/releases.md, docs/variants/protectli_vp66xx/overview.md
Update documentation about Intel ME status. Add note to each platform which has Intel ME disabled.
=> docs/variants: update Protectli documentation

docs/projects/trenchboot-aem-v2.md, docs/projects/trenchboot-aem.md
The documents used to have 'Trenchboot' in their titles, while the proper version is 'TrenchBoot'.
=> projects/trenchboot-aem*: fix TrenchBoot spelling

docs/guides/lab-assembly/msi-zx90.md, docs/guides/lab-assembly/protectli.md, docs/transparent-validation/rte/v1.1.0/flashing-guide.md, docs/variants/asus_kgpe_d16/setup.md
For more inf. check https://github.com/3mdeb/meta-rte/issues/80.
=> Add flash.sh script note

docs/kb/capsule-updates-configs.md
Follow up of https://github.com/Dasharo/docs/pull/950, which was a follow up of https://github.com/Dasharo/docs/pull/946. The last PR haven't changed the examples as Krystian noticed https://github.com/Dasharo/docs/pull/946#discussion_r1879806668
=> capsule-updates-configs.md: Fix example release RC version to 80, not FF

docs/dev-proc/versioning.md
Based on discussion in following issues and announcements made on DUG#6 new naming convention for Dasharo products was introduced. For details please check:
- https://github.com/Dasharo/docs/pull/820
- https://github.com/Dasharo/dasharo-issues/issues/762
=> dev-proc/versioning.md: initial coorections to dasharo naming scheme

docs/unified/novacustom/building-manual.md
https://github.com/Dasharo/dasharo-issues/issues/1143
Temporary fix. NS5x_TGL v1.5.2 release does not build on 2023 version of the container. Possibly there might be more versions which can't be build according to the instructions.
=> Novacustom building manual: Suggest using 2021 container if build fails

docs/variants/dell_optiplex/building-manual.md, docs/variants/dell_optiplex/initial-deployment.md
Walking through the recovery process I noticed some issues with the Optiplex documentation, namely:
- The Optiplex branch has been merged with Dasharo and coreboot upstream, so no need to mention it in `building-manual.md`
- `uefi-firmware-parser` only works with version `1.9` for whatever reason. I'll include logs of the errors I encountered below if it's helpful.
- There was a typo in the file path for the EC firmware which made it annoying to copy and paste
Here's that error I encountered with the latest version of `uefi-firmware` (`1.11`):
```
Dell PFSSection: 7439ed9e-70d3-4b65-9e33-1963a7ad3c37 spec 0x01 ts 0x00 type 0x00 version .8.1.72.3002 size 0x77b148 (7844168 bytes)
ME Container type= 0x10 version= 0x20 size= 0x30 (48 bytes) entires= 23 flags= 0xfffffc01
Traceback (most recent …
```
=> Update Optiplex documentation

docs/osf-trivia-list/dasharo-pro-package.md
The indentation level was either not enough of missing, which has led mkdocs to misinterpret the formatting.
***
This fixes https://docs.dasharo.com/osf-trivia-list/dasharo-pro-package/ page which gets linked relatively frequently.  It looked wrong to me for a while and I realized why only recently.
**Before:**
**After:**
=> osf-trivia-list/dasharo-pro-package.md: fix nested lists

docs/variants/overview.md
This PR introduces changes to improve the shop user experience. The shop section about DPP laptops may mislead users who have laptops other than NV41PZ. The proposed changes extend the product list to include the newest DPP for laptops (transition) for V560TU: https://shop.3mdeb.com/shop/dasharo-pro-package/dasharo-corebootuefi-transition-to-corebootheads-for-v560tu-laptops/
=> docs/variants/overview.md: add missing laptops shop product

docs/unified/protectli/overview.md
Breaking the line inserted four spacebars into the URL which made it return 404
=> protectli/overview.md: Fix link to 4670 revision check

docs/unified-test-documentation/dasharo-compatibility/319-nvidia-graphics.md, docs/unified/clevo/post-install.md, docs/unified/msi/hcl.md, docs/variants/msi_z690/releases.md, docs/variants/msi_z790/releases.md, docs/variants/novacustom_nv4x_tgl/releases.md, mkdocs.yml
Sort tests alphabetically for easier browsing (previously they were *roughly* sorted by ID), and replace `Coreboot` with `coreboot`.
=> Formatting fixes

docs/variants/protectli_vp2420/hardware-matrix.md
Added Qualcomm Atheros WiFi & goodram CX400 series SATA 2.5'' SSD, fixed SanDisk pendrive info.
=> docs/variants/protectli_vp2420/hardware-matrix.md: HW matrix update

docs/unified-test-documentation/dasharo-compatibility/31F-audio-subsystem.md, docs/unified-test-documentation/dasharo-compatibility/31H-usb-type-c.md
Change `All sound device` to `All sound devices` as it is correct windows option.
=> Fix a typo in audio tests description

docs/variants/qemu_q35/releases.md
The v0.2.0 release was not created using dasharo/dasharo, so it had to be manually copied from the previous version of the releases.md file
=> qemu_q35/releases.md: Add v0.2.1 release notes from dasharo/dasharo

docs/kb/edk2-capsule-updates.md, mkdocs.yml
This corrects small omissions and aligns the docs with changes in https://github.com/Dasharo/edk2/pull/267 and https://github.com/Dasharo/coreboot/pull/730.
*ref: ncm-1926*
=> Update documentation on capsule.sh and GenerateCapsules

docs/variants/dell_optiplex/overview.md
As discussed in https://github.com/Dasharo/dasharo-issues/issues/1427
Builds and looks fine, no new warning or info labels introduced
I didn't change the picture yet because of
1. copyright - I dont' have the machines so I can't take pictures
2. confusion - the picture in the [doc](https://docs.dasharo.com/variants/dell_optiplex/overview/) and at the [shop](https://shop.3mdeb.com/shop/dasharo-supported-hardware/dasharo-dell-optiplex-7010/) both show the DT version and @pietrushnic [says](https://github.com/Dasharo/dasharo-issues/issues/1182#issuecomment-3073053710) that the
> terminology [here](https://docs.dasharo.com/variants/overview/) is different than Dell, so what we mean by desktop or workstation does not have to reflect what the vendor meant.
but …
=> docs/variants/dell_optiplex/overview.md: distinguish hardware versions

docs/unified-test-documentation/generic-testing-stand-setup.md
Addresses the review of https://github.com/Dasharo/docs/pull/753
=> generic-testing-stand-setup.md updates

docs/dasharo-naming-convention.md
The https://www.seabios.org/SeaBIOS link leads to a 404 page. The same contents is available at https://www.seabios.org.
=> docs/dasharo-naming-convention.md: update SeaBIOS link

docs/variants/dell_optiplex/building-manual.md, docs/variants/dell_optiplex/initial-deployment.md
I tested this on Fedora 41 (with toolbox). As I still don't own the hardware in question I couldn't test if the resulting firmware is working as expected, but the layout looks as following (coreboot with SeaBIOS and TXT support):
fixes https://github.com/Dasharo/dasharo-issues/issues/1283
=> docs/variants/dell_optiplex: move and update firmware preparation

docs/variants/novacustom_nuc_box/releases.md
This platform does not use FSP from the blobs repo.
=> variants/novacustom_nuc_box/releases.md: remove FSP link

docs/dasharo-tools-suite/overview.md
For two reasons:
* Not to update it every time the key is being changed.
* Somebody may use older DTS releases and may want to find the key for them too.
=> docs: dasharo-tools-suite: overview.md: make DTS key inf generic

docs/unified/protectli/initial-deployment.md
The newest releases for every models were checked if they contain all the required flash regions and are not empty by:
- unpacking using `ifdtool -X`
- checking if not empty using `binwalk -E` Checked binaries:
- FW6C v1.0.14 - contains non-empty fd, bios, me
- V1210 v0.9.3 - contains non-empty fd, bios, me
- v1211 v0.9.3 - contains non-empty fd, bios, me
- v1410  v0.9.3 - contains non-empty fd, bios, me
- V1610 v0.9.3 - contains non-empty fd, bios, me
- VP2410 v1.1.1 - contains non-empty fd, bios (me not supported)
- VP2420 v1.2.1 - contains non-empty fd, bios, me
- VP2430 v0.9.0 - contans non-empty fd, bios, me
- VP2440 v0.9.0 - contains non-empty fd, bios, me
- VP32xx v0.9.0 - contains non-empty fd, bios, me
- VP46xx v1.2.0 - contains non-empty fd, bios, me
- VP66xx v0.9.2 - contains …
=> protectli/initial-deployment.md: Unify for all models
